FROM liquibase/liquibase:4.29

USER root

# Instalar curl en Debian/Ubuntu
RUN apt-get update \
    && apt-get install -y curl \
    && rm -rf /var/lib/apt/lists/*

# Descargar driver de Oracle desde Maven Central
RUN curl -L -o /liquibase/lib/ojdbc11.jar \
    https://repo1.maven.org/maven2/com/oracle/database/jdbc/ojdbc11/23.2.0.0/ojdbc11-23.2.0.0.jar

USER liquibase
ENTRYPOINT ["liquibase"]